import {
  AfterContentInit,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import { Pokemon } from '../models/pokemon.model';

@Component({
  selector: 'app-pokemon',
  templateUrl: './pokemon.component.html',
  styleUrls: ['./pokemon.component.css'],
})
export class PokemonComponent implements OnInit, AfterContentInit {
  @Input() currentPokemonNumber!: number;

  @Input() currentPokemon!: Pokemon;

  @Output() currentPokemonName = new EventEmitter<Pokemon>();

  public pokedex: Pokemon[] = [
    {
      id: 1,
      pic: '001.png',
      name: 'Bulbasaur',
      type: 'none',
      abilities: 'Overgrow, Chlorophyll',
      base_hp: 45,
      base_att: 49,
      base_def: 49,
      base_satt: 65,
      base_sdef: 65,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 2,
      pic: '002.png',
      name: 'Ivysaur',
      type: 'none',
      abilities: 'Overgrow, Chlorophyll',
      base_hp: 60,
      base_att: 62,
      base_def: 63,
      base_satt: 80,
      base_sdef: 80,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 3,
      pic: '003.png',
      name: 'Venusaur',
      type: 'none',
      abilities: 'Overgrow, Chlorophyll',
      base_hp: 80,
      base_att: 82,
      base_def: 83,
      base_satt: 100,
      base_sdef: 100,
      base_spd: 80,
      reward: 100,
    },
    {
      id: 4,
      pic: '004.png',
      name: 'Charmander',
      type: 'none',
      abilities: 'Blaze, Solar Power',
      base_hp: 39,
      base_att: 52,
      base_def: 43,
      base_satt: 60,
      base_sdef: 50,
      base_spd: 65,
      reward: 100,
    },
    {
      id: 5,
      pic: '005.png',
      name: 'Charmeleon',
      type: 'none',
      abilities: 'Blaze, Solar Power',
      base_hp: 58,
      base_att: 64,
      base_def: 58,
      base_satt: 80,
      base_sdef: 65,
      base_spd: 80,
      reward: 100,
    },
    {
      id: 6,
      pic: '006.png',
      name: 'Charizard',
      type: 'none',
      abilities: 'Blaze, Solar Power',
      base_hp: 78,
      base_att: 84,
      base_def: 78,
      base_satt: 109,
      base_sdef: 85,
      base_spd: 100,
      reward: 100,
    },
    {
      id: 7,
      pic: '007.png',
      name: 'Squirtle',
      type: 'none',
      abilities: 'Torrent, Rain Dish',
      base_hp: 44,
      base_att: 48,
      base_def: 65,
      base_satt: 50,
      base_sdef: 64,
      base_spd: 43,
      reward: 100,
    },
    {
      id: 8,
      pic: '008.png',
      name: 'Wartortle',
      type: 'none',
      abilities: 'Torrent, Rain Dish',
      base_hp: 59,
      base_att: 63,
      base_def: 80,
      base_satt: 65,
      base_sdef: 80,
      base_spd: 58,
      reward: 100,
    },
    {
      id: 9,
      pic: '009.png',
      name: 'Blastoise',
      type: 'none',
      abilities: 'Torrent, Rain Dish',
      base_hp: 79,
      base_att: 83,
      base_def: 100,
      base_satt: 85,
      base_sdef: 105,
      base_spd: 78,
      reward: 100,
    },
    {
      id: 10,
      pic: '010.png',
      name: 'Caterpie',
      type: 'none',
      abilities: 'Shield Dust, Run Away',
      base_hp: 45,
      base_att: 30,
      base_def: 35,
      base_satt: 20,
      base_sdef: 20,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 11,
      pic: '011.png',
      name: 'Metapod',
      type: 'none',
      abilities: 'Shed Skin',
      base_hp: 50,
      base_att: 20,
      base_def: 55,
      base_satt: 25,
      base_sdef: 25,
      base_spd: 30,
      reward: 100,
    },
    {
      id: 12,
      pic: '012.png',
      name: 'Butterfree',
      type: 'none',
      abilities: 'Compoundeyes, Tinted Lens',
      base_hp: 60,
      base_att: 45,
      base_def: 50,
      base_satt: 90,
      base_sdef: 80,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 13,
      pic: '013.png',
      name: 'Weedle',
      type: 'none',
      abilities: 'Shield Dust, Run Away',
      base_hp: 40,
      base_att: 35,
      base_def: 30,
      base_satt: 20,
      base_sdef: 20,
      base_spd: 50,
      reward: 100,
    },
    {
      id: 14,
      pic: '014.png',
      name: 'Kakuna',
      type: 'none',
      abilities: 'Shed Skin',
      base_hp: 45,
      base_att: 25,
      base_def: 50,
      base_satt: 25,
      base_sdef: 25,
      base_spd: 35,
      reward: 100,
    },
    {
      id: 15,
      pic: '015.png',
      name: 'Beedrill',
      type: 'none',
      abilities: 'Swarm, Sniper',
      base_hp: 65,
      base_att: 90,
      base_def: 40,
      base_satt: 45,
      base_sdef: 80,
      base_spd: 75,
      reward: 100,
    },
    {
      id: 16,
      pic: '016.png',
      name: 'Pidgey',
      type: 'none',
      abilities: 'Keen Eye, Tangled Feet, Big Pecks',
      base_hp: 40,
      base_att: 45,
      base_def: 40,
      base_satt: 35,
      base_sdef: 35,
      base_spd: 56,
      reward: 100,
    },
    {
      id: 17,
      pic: '017.png',
      name: 'Pidgeotto',
      type: 'none',
      abilities: 'Keen Eye, Tangled Feet, Big Pecks',
      base_hp: 63,
      base_att: 60,
      base_def: 55,
      base_satt: 50,
      base_sdef: 50,
      base_spd: 71,
      reward: 100,
    },
    {
      id: 18,
      pic: '018.png',
      name: 'Pidgeot',
      type: 'none',
      abilities: 'Keen Eye, Tangled Feet, Big Pecks',
      base_hp: 83,
      base_att: 80,
      base_def: 75,
      base_satt: 70,
      base_sdef: 70,
      base_spd: 101,
      reward: 100,
    },
    {
      id: 19,
      pic: '019.png',
      name: 'Rattata',
      type: 'none',
      abilities: 'Run Away, Guts, Hustle',
      base_hp: 30,
      base_att: 56,
      base_def: 35,
      base_satt: 25,
      base_sdef: 35,
      base_spd: 72,
      reward: 100,
    },
    {
      id: 20,
      pic: '020.png',
      name: 'Raticate',
      type: 'none',
      abilities: 'Run Away, Guts, Hustle',
      base_hp: 55,
      base_att: 81,
      base_def: 60,
      base_satt: 50,
      base_sdef: 70,
      base_spd: 97,
      reward: 100,
    },
    {
      id: 21,
      pic: '021.png',
      name: 'Spearow',
      type: 'none',
      abilities: 'Keen Eye, Sniper',
      base_hp: 40,
      base_att: 60,
      base_def: 30,
      base_satt: 31,
      base_sdef: 31,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 22,
      pic: '022.png',
      name: 'Fearow',
      type: 'none',
      abilities: 'Keen Eye, Sniper',
      base_hp: 65,
      base_att: 90,
      base_def: 65,
      base_satt: 61,
      base_sdef: 61,
      base_spd: 100,
      reward: 100,
    },
    {
      id: 23,
      pic: '023.png',
      name: 'Ekans',
      type: 'none',
      abilities: 'Intimidate, Shed Skin, Unnerve',
      base_hp: 35,
      base_att: 60,
      base_def: 44,
      base_satt: 40,
      base_sdef: 54,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 24,
      pic: '024.png',
      name: 'Arbok',
      type: 'none',
      abilities: 'Intimidate, Shed Skin, Unnerve',
      base_hp: 60,
      base_att: 95,
      base_def: 69,
      base_satt: 65,
      base_sdef: 79,
      base_spd: 80,
      reward: 100,
    },
    {
      id: 25,
      pic: '025.png',
      name: 'Pikachu',
      type: 'none',
      abilities: 'Static, Lightning Rod',
      base_hp: 35,
      base_att: 55,
      base_def: 40,
      base_satt: 50,
      base_sdef: 50,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 26,
      pic: '026.png',
      name: 'Raichu',
      type: 'none',
      abilities: 'Static, Lightning Rod',
      base_hp: 60,
      base_att: 90,
      base_def: 55,
      base_satt: 90,
      base_sdef: 80,
      base_spd: 110,
      reward: 100,
    },
    {
      id: 27,
      pic: '027.png',
      name: 'Sandshrew',
      type: 'none',
      abilities: 'Sand Veil, Sand Rush',
      base_hp: 50,
      base_att: 75,
      base_def: 85,
      base_satt: 20,
      base_sdef: 30,
      base_spd: 40,
      reward: 100,
    },
    {
      id: 28,
      pic: '028.png',
      name: 'Sandslash',
      type: 'none',
      abilities: 'Sand Veil, Sand Rush',
      base_hp: 75,
      base_att: 100,
      base_def: 110,
      base_satt: 45,
      base_sdef: 55,
      base_spd: 65,
      reward: 100,
    },
    {
      id: 29,
      pic: '029.png',
      name: 'Nidoran♀',
      type: 'none',
      abilities: 'Poison Point, Rivalry, Hustle',
      base_hp: 55,
      base_att: 47,
      base_def: 52,
      base_satt: 40,
      base_sdef: 40,
      base_spd: 41,
      reward: 100,
    },
    {
      id: 30,
      pic: '030.png',
      name: 'Nidorina',
      type: 'none',
      abilities: 'Poison Point, Rivalry, Hustle',
      base_hp: 70,
      base_att: 62,
      base_def: 67,
      base_satt: 55,
      base_sdef: 55,
      base_spd: 56,
      reward: 100,
    },
    {
      id: 31,
      pic: '031.png',
      name: 'Nidoqueen',
      type: 'none',
      abilities: 'Poison Point, Rivalry, Sheer Force',
      base_hp: 90,
      base_att: 92,
      base_def: 87,
      base_satt: 75,
      base_sdef: 85,
      base_spd: 76,
      reward: 100,
    },
    {
      id: 32,
      pic: '032.png',
      name: 'Nidoran♂',
      type: 'none',
      abilities: 'Poison Point, Rivalry, Hustle',
      base_hp: 46,
      base_att: 57,
      base_def: 40,
      base_satt: 40,
      base_sdef: 40,
      base_spd: 50,
      reward: 100,
    },
    {
      id: 33,
      pic: '033.png',
      name: 'Nidorino',
      type: 'none',
      abilities: 'Poison Point, Rivalry, Hustle',
      base_hp: 61,
      base_att: 72,
      base_def: 57,
      base_satt: 55,
      base_sdef: 55,
      base_spd: 65,
      reward: 100,
    },
    {
      id: 34,
      pic: '034.png',
      name: 'Nidoking',
      type: 'none',
      abilities: 'Poison Point, Rivalry, Sheer Force',
      base_hp: 81,
      base_att: 102,
      base_def: 77,
      base_satt: 85,
      base_sdef: 75,
      base_spd: 85,
      reward: 100,
    },
    {
      id: 35,
      pic: '035.png',
      name: 'Clefairy',
      type: 'none',
      abilities: 'Cute Charm, Magic Guard, Friend Guard',
      base_hp: 70,
      base_att: 45,
      base_def: 48,
      base_satt: 60,
      base_sdef: 65,
      base_spd: 35,
      reward: 100,
    },
    {
      id: 36,
      pic: '036.png',
      name: 'Clefable',
      type: 'none',
      abilities: 'Cute Charm, Magic Guard, Unaware',
      base_hp: 95,
      base_att: 70,
      base_def: 73,
      base_satt: 95,
      base_sdef: 90,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 37,
      pic: '037.png',
      name: 'Vulpix',
      type: 'none',
      abilities: 'Flash Fire, Drought',
      base_hp: 38,
      base_att: 41,
      base_def: 40,
      base_satt: 50,
      base_sdef: 65,
      base_spd: 65,
      reward: 100,
    },
    {
      id: 38,
      pic: '038.png',
      name: 'Ninetales',
      type: 'none',
      abilities: 'Flash Fire, Drought',
      base_hp: 73,
      base_att: 76,
      base_def: 75,
      base_satt: 81,
      base_sdef: 100,
      base_spd: 100,
      reward: 100,
    },
    {
      id: 39,
      pic: '039.png',
      name: 'Jigglypuff',
      type: 'none',
      abilities: 'Cute Charm, Competitive, Friend Guard',
      base_hp: 115,
      base_att: 45,
      base_def: 20,
      base_satt: 45,
      base_sdef: 25,
      base_spd: 20,
      reward: 100,
    },
    {
      id: 40,
      pic: '040.png',
      name: 'Wigglytuff',
      type: 'none',
      abilities: 'Cute Charm, Competitive, Frisk',
      base_hp: 140,
      base_att: 70,
      base_def: 45,
      base_satt: 85,
      base_sdef: 50,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 41,
      pic: '041.png',
      name: 'Zubat',
      type: 'none',
      abilities: 'Inner Focus, Infiltrator',
      base_hp: 40,
      base_att: 45,
      base_def: 35,
      base_satt: 30,
      base_sdef: 40,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 42,
      pic: '042.png',
      name: 'Golbat',
      type: 'none',
      abilities: 'Inner Focus, Infiltrator',
      base_hp: 75,
      base_att: 80,
      base_def: 70,
      base_satt: 65,
      base_sdef: 75,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 43,
      pic: '043.png',
      name: 'Oddish',
      type: 'none',
      abilities: 'Chlorophyll, Run Away',
      base_hp: 45,
      base_att: 50,
      base_def: 55,
      base_satt: 75,
      base_sdef: 65,
      base_spd: 30,
      reward: 100,
    },
    {
      id: 44,
      pic: '044.png',
      name: 'Gloom',
      type: 'none',
      abilities: 'Chlorophyll, Stench',
      base_hp: 60,
      base_att: 65,
      base_def: 70,
      base_satt: 85,
      base_sdef: 75,
      base_spd: 40,
      reward: 100,
    },
    {
      id: 45,
      pic: '045.png',
      name: 'Vileplume',
      type: 'none',
      abilities: 'Chlorophyll, Effect Spore',
      base_hp: 75,
      base_att: 80,
      base_def: 85,
      base_satt: 110,
      base_sdef: 90,
      base_spd: 50,
      reward: 100,
    },
    {
      id: 46,
      pic: '046.png',
      name: 'Paras',
      type: 'none',
      abilities: 'Effect Spore, Dry Skin, Damp',
      base_hp: 35,
      base_att: 70,
      base_def: 55,
      base_satt: 45,
      base_sdef: 55,
      base_spd: 25,
      reward: 100,
    },
    {
      id: 47,
      pic: '047.png',
      name: 'Parasect',
      type: 'none',
      abilities: 'Effect Spore, Dry Skin, Damp',
      base_hp: 60,
      base_att: 95,
      base_def: 80,
      base_satt: 60,
      base_sdef: 80,
      base_spd: 30,
      reward: 100,
    },
    {
      id: 48,
      pic: '048.png',
      name: 'Venonat',
      type: 'none',
      abilities: 'Compoundeyes, Tinted Lens, Run Away',
      base_hp: 60,
      base_att: 55,
      base_def: 50,
      base_satt: 40,
      base_sdef: 55,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 49,
      pic: '049.png',
      name: 'Venomoth',
      type: 'none',
      abilities: 'Shield Dust, Tinted Lens, Wonder Skin',
      base_hp: 70,
      base_att: 65,
      base_def: 60,
      base_satt: 90,
      base_sdef: 75,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 50,
      pic: '050.png',
      name: 'Diglett',
      type: 'none',
      abilities: 'Sand Veil, Arena Trap, Sand Force',
      base_hp: 10,
      base_att: 55,
      base_def: 25,
      base_satt: 35,
      base_sdef: 45,
      base_spd: 95,
      reward: 100,
    },
    {
      id: 51,
      pic: '051.png',
      name: 'Dugtrio',
      type: 'none',
      abilities: 'Sand Veil, Arena Trap, Sand Force',
      base_hp: 35,
      base_att: 100,
      base_def: 50,
      base_satt: 50,
      base_sdef: 70,
      base_spd: 120,
      reward: 100,
    },
    {
      id: 52,
      pic: '052.png',
      name: 'Meowth',
      type: 'none',
      abilities: 'Pickup, Technician, Unnerve',
      base_hp: 40,
      base_att: 45,
      base_def: 35,
      base_satt: 40,
      base_sdef: 40,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 53,
      pic: '053.png',
      name: 'Persian',
      type: 'none',
      abilities: 'Limber, Technician, Unnerve',
      base_hp: 65,
      base_att: 70,
      base_def: 60,
      base_satt: 65,
      base_sdef: 65,
      base_spd: 115,
      reward: 100,
    },
    {
      id: 54,
      pic: '054.png',
      name: 'Psyduck',
      type: 'none',
      abilities: 'Damp, Cloud Nine, Swift Swim',
      base_hp: 50,
      base_att: 52,
      base_def: 48,
      base_satt: 65,
      base_sdef: 50,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 55,
      pic: '055.png',
      name: 'Golduck',
      type: 'none',
      abilities: 'Damp, Cloud Nine, Swift Swim',
      base_hp: 80,
      base_att: 82,
      base_def: 78,
      base_satt: 95,
      base_sdef: 80,
      base_spd: 85,
      reward: 100,
    },
    {
      id: 56,
      pic: '056.png',
      name: 'Mankey',
      type: 'none',
      abilities: 'Vital Spirit, Anger Point, Defiant',
      base_hp: 40,
      base_att: 80,
      base_def: 35,
      base_satt: 35,
      base_sdef: 45,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 57,
      pic: '057.png',
      name: 'Primeape',
      type: 'none',
      abilities: 'Vital Spirit, Anger Point, Defiant',
      base_hp: 65,
      base_att: 105,
      base_def: 60,
      base_satt: 60,
      base_sdef: 70,
      base_spd: 95,
      reward: 100,
    },
    {
      id: 58,
      pic: '058.png',
      name: 'Growlithe',
      type: 'none',
      abilities: 'Intimidate, Flash Fire, Justified',
      base_hp: 55,
      base_att: 70,
      base_def: 45,
      base_satt: 70,
      base_sdef: 50,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 59,
      pic: '059.png',
      name: 'Arcanine',
      type: 'none',
      abilities: 'Intimidate, Flash Fire, Justified',
      base_hp: 90,
      base_att: 110,
      base_def: 80,
      base_satt: 100,
      base_sdef: 80,
      base_spd: 95,
      reward: 100,
    },
    {
      id: 60,
      pic: '060.png',
      name: 'Poliwag',
      type: 'none',
      abilities: 'Water Absorb, Damp, Swift Swim',
      base_hp: 40,
      base_att: 50,
      base_def: 40,
      base_satt: 40,
      base_sdef: 40,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 61,
      pic: '061.png',
      name: 'Poliwhirl',
      type: 'none',
      abilities: 'Water Absorb, Damp, Swift Swim',
      base_hp: 65,
      base_att: 65,
      base_def: 65,
      base_satt: 50,
      base_sdef: 50,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 62,
      pic: '062.png',
      name: 'Poliwrath',
      type: 'none',
      abilities: 'Water Absorb, Damp, Swift Swim',
      base_hp: 90,
      base_att: 95,
      base_def: 95,
      base_satt: 70,
      base_sdef: 90,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 63,
      pic: '063.png',
      name: 'Abra',
      type: 'none',
      abilities: 'Synchronize, Inner Focus, Magic Guard',
      base_hp: 25,
      base_att: 20,
      base_def: 15,
      base_satt: 105,
      base_sdef: 55,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 64,
      pic: '064.png',
      name: 'Kadabra',
      type: 'none',
      abilities: 'Synchronize, Inner Focus, Magic Guard',
      base_hp: 40,
      base_att: 35,
      base_def: 30,
      base_satt: 120,
      base_sdef: 70,
      base_spd: 105,
      reward: 100,
    },
    {
      id: 65,
      pic: '065.png',
      name: 'Alakazam',
      type: 'none',
      abilities: 'Synchronize, Inner Focus, Magic Guard',
      base_hp: 55,
      base_att: 50,
      base_def: 45,
      base_satt: 135,
      base_sdef: 95,
      base_spd: 120,
      reward: 100,
    },
    {
      id: 66,
      pic: '066.png',
      name: 'Machop',
      type: 'none',
      abilities: 'Guts, No Guard, Steadfast',
      base_hp: 70,
      base_att: 80,
      base_def: 50,
      base_satt: 35,
      base_sdef: 35,
      base_spd: 35,
      reward: 100,
    },
    {
      id: 67,
      pic: '067.png',
      name: 'Machoke',
      type: 'none',
      abilities: 'Guts, No Guard, Steadfast',
      base_hp: 80,
      base_att: 100,
      base_def: 70,
      base_satt: 50,
      base_sdef: 60,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 68,
      pic: '068.png',
      name: 'Machamp',
      type: 'none',
      abilities: 'Guts, No Guard, Steadfast',
      base_hp: 90,
      base_att: 130,
      base_def: 80,
      base_satt: 65,
      base_sdef: 85,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 69,
      pic: '069.png',
      name: 'Bellsprout',
      type: 'none',
      abilities: 'Chlorophyll, Gluttony',
      base_hp: 50,
      base_att: 75,
      base_def: 35,
      base_satt: 70,
      base_sdef: 30,
      base_spd: 40,
      reward: 100,
    },
    {
      id: 70,
      pic: '070.png',
      name: 'Weepinbell',
      type: 'none',
      abilities: 'Chlorophyll, Gluttony',
      base_hp: 65,
      base_att: 90,
      base_def: 50,
      base_satt: 85,
      base_sdef: 45,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 71,
      pic: '071.png',
      name: 'Victreebel',
      type: 'none',
      abilities: 'Chlorophyll, Gluttony',
      base_hp: 80,
      base_att: 105,
      base_def: 65,
      base_satt: 100,
      base_sdef: 70,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 72,
      pic: '072.png',
      name: 'Tentacool',
      type: 'none',
      abilities: 'Clear Body, Liquid Ooze, Rain Dish',
      base_hp: 40,
      base_att: 40,
      base_def: 35,
      base_satt: 50,
      base_sdef: 100,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 73,
      pic: '073.png',
      name: 'Tentacruel',
      type: 'none',
      abilities: 'Clear Body, Liquid Ooze, Rain Dish',
      base_hp: 80,
      base_att: 70,
      base_def: 65,
      base_satt: 80,
      base_sdef: 120,
      base_spd: 100,
      reward: 100,
    },
    {
      id: 74,
      pic: '074.png',
      name: 'Geodude',
      type: 'none',
      abilities: 'Rock Head, Sturdy, Sand Veil',
      base_hp: 40,
      base_att: 80,
      base_def: 100,
      base_satt: 30,
      base_sdef: 30,
      base_spd: 20,
      reward: 100,
    },
    {
      id: 75,
      pic: '075.png',
      name: 'Graveler',
      type: 'none',
      abilities: 'Rock Head, Sturdy, Sand Veil',
      base_hp: 55,
      base_att: 95,
      base_def: 115,
      base_satt: 45,
      base_sdef: 45,
      base_spd: 35,
      reward: 100,
    },
    {
      id: 76,
      pic: '076.png',
      name: 'Golem',
      type: 'none',
      abilities: 'Rock Head, Sturdy, Sand Veil',
      base_hp: 80,
      base_att: 120,
      base_def: 130,
      base_satt: 55,
      base_sdef: 65,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 77,
      pic: '077.png',
      name: 'Ponyta',
      type: 'none',
      abilities: 'Run Away, Flash Fire, Flame Body',
      base_hp: 50,
      base_att: 85,
      base_def: 55,
      base_satt: 65,
      base_sdef: 65,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 78,
      pic: '078.png',
      name: 'Rapidash',
      type: 'none',
      abilities: 'Run Away, Flash Fire, Flame Body',
      base_hp: 65,
      base_att: 100,
      base_def: 70,
      base_satt: 80,
      base_sdef: 80,
      base_spd: 105,
      reward: 100,
    },
    {
      id: 79,
      pic: '079.png',
      name: 'Slowpoke',
      type: 'none',
      abilities: 'Oblivious, Own Tempo, Regenerator',
      base_hp: 90,
      base_att: 65,
      base_def: 65,
      base_satt: 40,
      base_sdef: 40,
      base_spd: 15,
      reward: 100,
    },
    {
      id: 80,
      pic: '080.png',
      name: 'Slowbro',
      type: 'none',
      abilities: 'Oblivious, Own Tempo, Regenerator',
      base_hp: 95,
      base_att: 75,
      base_def: 110,
      base_satt: 100,
      base_sdef: 80,
      base_spd: 30,
      reward: 100,
    },
    {
      id: 81,
      pic: '081.png',
      name: 'Magnemite',
      type: 'none',
      abilities: 'Magnet Pull, Sturdy, Analytic',
      base_hp: 25,
      base_att: 35,
      base_def: 70,
      base_satt: 95,
      base_sdef: 55,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 82,
      pic: '082.png',
      name: 'Magneton',
      type: 'none',
      abilities: 'Magnet Pull, Sturdy, Analytic',
      base_hp: 50,
      base_att: 60,
      base_def: 95,
      base_satt: 120,
      base_sdef: 70,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 83,
      pic: '083.png',
      name: "Farfetch'd",
      type: 'none',
      abilities: 'Keen Eye, Inner Focus, Defiant',
      base_hp: 52,
      base_att: 90,
      base_def: 55,
      base_satt: 58,
      base_sdef: 62,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 84,
      pic: '084.png',
      name: 'Doduo',
      type: 'none',
      abilities: 'Run Away, Early Bird, Tangled Feet',
      base_hp: 35,
      base_att: 85,
      base_def: 45,
      base_satt: 35,
      base_sdef: 35,
      base_spd: 75,
      reward: 100,
    },
    {
      id: 85,
      pic: '085.png',
      name: 'Dodrio',
      type: 'none',
      abilities: 'Run Away, Early Bird, Tangled Feet',
      base_hp: 60,
      base_att: 110,
      base_def: 70,
      base_satt: 60,
      base_sdef: 60,
      base_spd: 110,
      reward: 100,
    },
    {
      id: 86,
      pic: '086.png',
      name: 'Seel',
      type: 'none',
      abilities: 'Thick Fat, Hydration, Ice Body',
      base_hp: 65,
      base_att: 45,
      base_def: 55,
      base_satt: 45,
      base_sdef: 70,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 87,
      pic: '087.png',
      name: 'Dewgong',
      type: 'none',
      abilities: 'Thick Fat, Hydration, Ice Body',
      base_hp: 90,
      base_att: 70,
      base_def: 80,
      base_satt: 70,
      base_sdef: 95,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 88,
      pic: '088.png',
      name: 'Grimer',
      type: 'none',
      abilities: 'Stench, Sticky Hold, Poison Touch',
      base_hp: 80,
      base_att: 80,
      base_def: 50,
      base_satt: 40,
      base_sdef: 50,
      base_spd: 25,
      reward: 100,
    },
    {
      id: 89,
      pic: '089.png',
      name: 'Muk',
      type: 'none',
      abilities: 'Stench, Sticky Hold, Poison Touch',
      base_hp: 105,
      base_att: 105,
      base_def: 75,
      base_satt: 65,
      base_sdef: 100,
      base_spd: 50,
      reward: 100,
    },
    {
      id: 90,
      pic: '090.png',
      name: 'Shellder',
      type: 'none',
      abilities: 'Shell Armor, Skill Link, Overcoat',
      base_hp: 30,
      base_att: 65,
      base_def: 100,
      base_satt: 45,
      base_sdef: 25,
      base_spd: 40,
      reward: 100,
    },
    {
      id: 91,
      pic: '091.png',
      name: 'Cloyster',
      type: 'none',
      abilities: 'Shell Armor, Skill Link, Overcoat',
      base_hp: 50,
      base_att: 95,
      base_def: 180,
      base_satt: 85,
      base_sdef: 45,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 92,
      pic: '092.png',
      name: 'Gastly',
      type: 'none',
      abilities: 'Levitate',
      base_hp: 30,
      base_att: 35,
      base_def: 30,
      base_satt: 100,
      base_sdef: 35,
      base_spd: 80,
      reward: 100,
    },
    {
      id: 93,
      pic: '093.png',
      name: 'Haunter',
      type: 'none',
      abilities: 'Levitate',
      base_hp: 45,
      base_att: 50,
      base_def: 45,
      base_satt: 115,
      base_sdef: 55,
      base_spd: 95,
      reward: 100,
    },
    {
      id: 94,
      pic: '094.png',
      name: 'Gengar',
      type: 'none',
      abilities: 'Cursed Body',
      base_hp: 60,
      base_att: 65,
      base_def: 60,
      base_satt: 130,
      base_sdef: 75,
      base_spd: 110,
      reward: 100,
    },
    {
      id: 95,
      pic: '095.png',
      name: 'Onix',
      type: 'none',
      abilities: 'Rock Head, Sturdy, Weak Armor',
      base_hp: 35,
      base_att: 45,
      base_def: 160,
      base_satt: 30,
      base_sdef: 45,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 96,
      pic: '096.png',
      name: 'Drowzee',
      type: 'none',
      abilities: 'Insomnia, Forewarn, Inner Focus',
      base_hp: 60,
      base_att: 48,
      base_def: 45,
      base_satt: 43,
      base_sdef: 90,
      base_spd: 42,
      reward: 100,
    },
    {
      id: 97,
      pic: '097.png',
      name: 'Hypno',
      type: 'none',
      abilities: 'Insomnia, Forewarn, Inner Focus',
      base_hp: 85,
      base_att: 73,
      base_def: 70,
      base_satt: 73,
      base_sdef: 115,
      base_spd: 67,
      reward: 100,
    },
    {
      id: 98,
      pic: '098.png',
      name: 'Krabby',
      type: 'none',
      abilities: 'Hyper Cutter, Shell Armor, Sheer Force',
      base_hp: 30,
      base_att: 105,
      base_def: 90,
      base_satt: 25,
      base_sdef: 25,
      base_spd: 50,
      reward: 100,
    },
    {
      id: 99,
      pic: '099.png',
      name: 'Kingler',
      type: 'none',
      abilities: 'Hyper Cutter, Shell Armor, Sheer Force',
      base_hp: 55,
      base_att: 130,
      base_def: 115,
      base_satt: 50,
      base_sdef: 50,
      base_spd: 75,
      reward: 100,
    },
    {
      id: 100,
      pic: '100.png',
      name: 'Voltorb',
      type: 'none',
      abilities: 'Soundproof, Static, Aftermath',
      base_hp: 40,
      base_att: 30,
      base_def: 50,
      base_satt: 55,
      base_sdef: 55,
      base_spd: 100,
      reward: 100,
    },
    {
      id: 101,
      pic: '101.png',
      name: 'Electrode',
      type: 'none',
      abilities: 'Soundproof, Static, Aftermath',
      base_hp: 60,
      base_att: 50,
      base_def: 70,
      base_satt: 80,
      base_sdef: 80,
      base_spd: 150,
      reward: 100,
    },
    {
      id: 102,
      pic: '102.png',
      name: 'Exeggcute',
      type: 'none',
      abilities: 'Chlorophyll, Harvest',
      base_hp: 60,
      base_att: 40,
      base_def: 80,
      base_satt: 60,
      base_sdef: 45,
      base_spd: 40,
      reward: 100,
    },
    {
      id: 103,
      pic: '103.png',
      name: 'Exeggutor',
      type: 'none',
      abilities: 'Chlorophyll, Harvest',
      base_hp: 95,
      base_att: 95,
      base_def: 85,
      base_satt: 125,
      base_sdef: 75,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 104,
      pic: '104.png',
      name: 'Cubone',
      type: 'none',
      abilities: 'Rock Head, Lightning Rod, Battle Armor',
      base_hp: 50,
      base_att: 50,
      base_def: 95,
      base_satt: 40,
      base_sdef: 50,
      base_spd: 35,
      reward: 100,
    },
    {
      id: 105,
      pic: '105.png',
      name: 'Marowak',
      type: 'none',
      abilities: 'Rock Head, Lightning Rod, Battle Armor',
      base_hp: 60,
      base_att: 80,
      base_def: 110,
      base_satt: 50,
      base_sdef: 80,
      base_spd: 45,
      reward: 100,
    },
    {
      id: 106,
      pic: '106.png',
      name: 'Hitmonlee',
      type: 'none',
      abilities: 'Limber, Reckless, Unburden',
      base_hp: 50,
      base_att: 120,
      base_def: 53,
      base_satt: 35,
      base_sdef: 110,
      base_spd: 87,
      reward: 100,
    },
    {
      id: 107,
      pic: '107.png',
      name: 'Hitmonchan',
      type: 'none',
      abilities: 'Keen Eye, Iron Fist, Inner Focus',
      base_hp: 50,
      base_att: 105,
      base_def: 79,
      base_satt: 35,
      base_sdef: 110,
      base_spd: 76,
      reward: 100,
    },
    {
      id: 108,
      pic: '108.png',
      name: 'Lickitung',
      type: 'none',
      abilities: 'Own Tempo, Oblivious, Cloud Nine',
      base_hp: 90,
      base_att: 55,
      base_def: 75,
      base_satt: 60,
      base_sdef: 75,
      base_spd: 30,
      reward: 100,
    },
    {
      id: 109,
      pic: '109.png',
      name: 'Koffing',
      type: 'none',
      abilities: 'Levitate, Neutralizing Gas, Stench',
      base_hp: 40,
      base_att: 65,
      base_def: 95,
      base_satt: 60,
      base_sdef: 45,
      base_spd: 35,
      reward: 100,
    },
    {
      id: 110,
      pic: '110.png',
      name: 'Weezing',
      type: 'none',
      abilities: 'Levitate, Neutralizing Gas, Stench',
      base_hp: 65,
      base_att: 90,
      base_def: 120,
      base_satt: 85,
      base_sdef: 70,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 111,
      pic: '111.png',
      name: 'Rhyhorn',
      type: 'none',
      abilities: 'Lightning Rod, Rock Head, Reckless',
      base_hp: 80,
      base_att: 85,
      base_def: 95,
      base_satt: 30,
      base_sdef: 30,
      base_spd: 25,
      reward: 100,
    },
    {
      id: 112,
      pic: '112.png',
      name: 'Rhydon',
      type: 'none',
      abilities: 'Lightning Rod, Rock Head, Reckless',
      base_hp: 105,
      base_att: 130,
      base_def: 120,
      base_satt: 45,
      base_sdef: 45,
      base_spd: 40,
      reward: 100,
    },
    {
      id: 113,
      pic: '113.png',
      name: 'Chansey',
      type: 'none',
      abilities: 'Natural Cure, Serene Grace, Healer',
      base_hp: 250,
      base_att: 5,
      base_def: 5,
      base_satt: 35,
      base_sdef: 105,
      base_spd: 50,
      reward: 100,
    },
    {
      id: 114,
      pic: '114.png',
      name: 'Tangela',
      type: 'none',
      abilities: 'Chlorophyll, Leaf Guard, Regenerator',
      base_hp: 65,
      base_att: 55,
      base_def: 115,
      base_satt: 100,
      base_sdef: 40,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 115,
      pic: '115.png',
      name: 'Kangaskhan',
      type: 'none',
      abilities: 'Early Bird, Scrappy, Inner Focus',
      base_hp: 105,
      base_att: 95,
      base_def: 80,
      base_satt: 40,
      base_sdef: 80,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 116,
      pic: '116.png',
      name: 'Horsea',
      type: 'none',
      abilities: 'Swift Swim, Sniper, Damp',
      base_hp: 30,
      base_att: 40,
      base_def: 70,
      base_satt: 70,
      base_sdef: 25,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 117,
      pic: '117.png',
      name: 'Seadra',
      type: 'none',
      abilities: 'Poison Point, Sniper, Damp',
      base_hp: 55,
      base_att: 65,
      base_def: 95,
      base_satt: 95,
      base_sdef: 45,
      base_spd: 85,
      reward: 100,
    },
    {
      id: 118,
      pic: '118.png',
      name: 'Goldeen',
      type: 'none',
      abilities: 'Swift Swim, Water Veil, Lightning Rod',
      base_hp: 45,
      base_att: 67,
      base_def: 60,
      base_satt: 35,
      base_sdef: 50,
      base_spd: 63,
      reward: 100,
    },
    {
      id: 119,
      pic: '119.png',
      name: 'Seaking',
      type: 'none',
      abilities: 'Swift Swim, Water Veil, Lightning Rod',
      base_hp: 80,
      base_att: 92,
      base_def: 65,
      base_satt: 65,
      base_sdef: 80,
      base_spd: 68,
      reward: 100,
    },
    {
      id: 120,
      pic: '120.png',
      name: 'Staryu',
      type: 'none',
      abilities: 'Illuminate, Natural Cure, Analytic',
      base_hp: 30,
      base_att: 45,
      base_def: 55,
      base_satt: 70,
      base_sdef: 55,
      base_spd: 85,
      reward: 100,
    },
    {
      id: 121,
      pic: '121.png',
      name: 'Starmie',
      type: 'none',
      abilities: 'Illuminate, Natural Cure, Analytic',
      base_hp: 60,
      base_att: 75,
      base_def: 85,
      base_satt: 100,
      base_sdef: 85,
      base_spd: 115,
      reward: 100,
    },
    {
      id: 122,
      pic: '122.png',
      name: 'Mr. Mime',
      type: 'none',
      abilities: 'Soundproof, Filter, Technician',
      base_hp: 40,
      base_att: 45,
      base_def: 65,
      base_satt: 100,
      base_sdef: 120,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 123,
      pic: '123.png',
      name: 'Scyther',
      type: 'none',
      abilities: 'Swarm, Technician, Steadfast',
      base_hp: 70,
      base_att: 110,
      base_def: 80,
      base_satt: 55,
      base_sdef: 80,
      base_spd: 105,
      reward: 100,
    },
    {
      id: 124,
      pic: '124.png',
      name: 'Jynx',
      type: 'none',
      abilities: 'Oblivious, Forewarn, Dry Skin',
      base_hp: 65,
      base_att: 50,
      base_def: 35,
      base_satt: 115,
      base_sdef: 95,
      base_spd: 95,
      reward: 100,
    },
    {
      id: 125,
      pic: '125.png',
      name: 'Electabuzz',
      type: 'none',
      abilities: 'Static, Vital Spirit',
      base_hp: 65,
      base_att: 83,
      base_def: 57,
      base_satt: 95,
      base_sdef: 85,
      base_spd: 105,
      reward: 100,
    },
    {
      id: 126,
      pic: '126.png',
      name: 'Magmar',
      type: 'none',
      abilities: 'Flame Body, Vital Spirit',
      base_hp: 65,
      base_att: 95,
      base_def: 57,
      base_satt: 100,
      base_sdef: 85,
      base_spd: 93,
      reward: 100,
    },
    {
      id: 127,
      pic: '127.png',
      name: 'Pinsir',
      type: 'none',
      abilities: 'Hyper Cutter, Mold Breaker, Moxie',
      base_hp: 65,
      base_att: 125,
      base_def: 100,
      base_satt: 55,
      base_sdef: 70,
      base_spd: 85,
      reward: 100,
    },
    {
      id: 128,
      pic: '128.png',
      name: 'Tauros',
      type: 'none',
      abilities: 'Intimidate, Anger Point, Sheer Force',
      base_hp: 75,
      base_att: 100,
      base_def: 95,
      base_satt: 40,
      base_sdef: 70,
      base_spd: 110,
      reward: 100,
    },
    {
      id: 129,
      pic: '129.png',
      name: 'Magikarp',
      type: 'none',
      abilities: 'Swift Swim, Rattled',
      base_hp: 20,
      base_att: 10,
      base_def: 55,
      base_satt: 15,
      base_sdef: 20,
      base_spd: 80,
      reward: 100,
    },
    {
      id: 130,
      pic: '130.png',
      name: 'Gyarados',
      type: 'none',
      abilities: 'Intimidate, Moxie',
      base_hp: 95,
      base_att: 125,
      base_def: 79,
      base_satt: 60,
      base_sdef: 100,
      base_spd: 81,
      reward: 100,
    },
    {
      id: 131,
      pic: '131.png',
      name: 'Lapras',
      type: 'none',
      abilities: 'Water Absorb, Shell Armor, Hydration',
      base_hp: 130,
      base_att: 85,
      base_def: 80,
      base_satt: 85,
      base_sdef: 95,
      base_spd: 60,
      reward: 100,
    },
    {
      id: 132,
      pic: '132.png',
      name: 'Ditto',
      type: 'none',
      abilities: 'Limber, Imposter',
      base_hp: 48,
      base_att: 48,
      base_def: 48,
      base_satt: 48,
      base_sdef: 48,
      base_spd: 48,
      reward: 100,
    },
    {
      id: 133,
      pic: '133.png',
      name: 'Eevee',
      type: 'none',
      abilities: 'Run Away, Adaptability, Anticipation',
      base_hp: 55,
      base_att: 55,
      base_def: 50,
      base_satt: 45,
      base_sdef: 65,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 134,
      pic: '134.png',
      name: 'Vaporeon',
      type: 'none',
      abilities: 'Water Absorb, Hydration',
      base_hp: 130,
      base_att: 65,
      base_def: 60,
      base_satt: 110,
      base_sdef: 95,
      base_spd: 65,
      reward: 100,
    },
    {
      id: 135,
      pic: '135.png',
      name: 'Jolteon',
      type: 'none',
      abilities: 'Volt Absorb, Quick Feet',
      base_hp: 65,
      base_att: 65,
      base_def: 60,
      base_satt: 110,
      base_sdef: 95,
      base_spd: 130,
      reward: 100,
    },
    {
      id: 136,
      pic: '136.png',
      name: 'Flareon',
      type: 'none',
      abilities: 'Flash Fire, Guts',
      base_hp: 65,
      base_att: 130,
      base_def: 60,
      base_satt: 95,
      base_sdef: 110,
      base_spd: 65,
      reward: 100,
    },
    {
      id: 137,
      pic: '137.png',
      name: 'Porygon',
      type: 'none',
      abilities: 'Trace, Download, Analytic',
      base_hp: 65,
      base_att: 60,
      base_def: 70,
      base_satt: 85,
      base_sdef: 75,
      base_spd: 40,
      reward: 100,
    },
    {
      id: 138,
      pic: '138.png',
      name: 'Omanyte',
      type: 'none',
      abilities: 'Swift Swim, Shell Armor, Weak Armor',
      base_hp: 35,
      base_att: 40,
      base_def: 100,
      base_satt: 90,
      base_sdef: 55,
      base_spd: 35,
      reward: 100,
    },
    {
      id: 139,
      pic: '139.png',
      name: 'Omastar',
      type: 'none',
      abilities: 'Swift Swim, Shell Armor, Weak Armor',
      base_hp: 70,
      base_att: 60,
      base_def: 125,
      base_satt: 115,
      base_sdef: 70,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 140,
      pic: '140.png',
      name: 'Kabuto',
      type: 'none',
      abilities: 'Swift Swim, Battle Armor, Weak Armor',
      base_hp: 30,
      base_att: 80,
      base_def: 90,
      base_satt: 55,
      base_sdef: 45,
      base_spd: 55,
      reward: 100,
    },
    {
      id: 141,
      pic: '141.png',
      name: 'Kabutops',
      type: 'none',
      abilities: 'Swift Swim, Battle Armor, Weak Armor',
      base_hp: 60,
      base_att: 115,
      base_def: 105,
      base_satt: 65,
      base_sdef: 70,
      base_spd: 80,
      reward: 100,
    },
    {
      id: 142,
      pic: '142.png',
      name: 'Aerodactyl',
      type: 'none',
      abilities: 'Rock Head, Pressure, Unnerve',
      base_hp: 80,
      base_att: 105,
      base_def: 65,
      base_satt: 60,
      base_sdef: 75,
      base_spd: 130,
      reward: 100,
    },
    {
      id: 143,
      pic: '143.png',
      name: 'Snorlax',
      type: 'none',
      abilities: 'Immunity, Thick Fat, Gluttony',
      base_hp: 160,
      base_att: 110,
      base_def: 65,
      base_satt: 65,
      base_sdef: 110,
      base_spd: 30,
      reward: 100,
    },
    {
      id: 144,
      pic: '144.png',
      name: 'Articuno',
      type: 'none',
      abilities: 'Pressure, Snow Cloak',
      base_hp: 90,
      base_att: 85,
      base_def: 100,
      base_satt: 95,
      base_sdef: 125,
      base_spd: 85,
      reward: 100,
    },
    {
      id: 145,
      pic: '145.png',
      name: 'Zapdos',
      type: 'none',
      abilities: 'Pressure, Static',
      base_hp: 90,
      base_att: 90,
      base_def: 85,
      base_satt: 125,
      base_sdef: 90,
      base_spd: 100,
      reward: 100,
    },
    {
      id: 146,
      pic: '146.png',
      name: 'Moltres',
      type: 'none',
      abilities: 'Pressure, Flame Body',
      base_hp: 90,
      base_att: 100,
      base_def: 90,
      base_satt: 125,
      base_sdef: 85,
      base_spd: 90,
      reward: 100,
    },
    {
      id: 147,
      pic: '147.png',
      name: 'Dratini',
      type: 'none',
      abilities: 'Shed Skin, Marvel Scale',
      base_hp: 41,
      base_att: 64,
      base_def: 45,
      base_satt: 50,
      base_sdef: 50,
      base_spd: 50,
      reward: 100,
    },
    {
      id: 148,
      pic: '148.png',
      name: 'Dragonair',
      type: 'none',
      abilities: 'Shed Skin, Marvel Scale',
      base_hp: 61,
      base_att: 84,
      base_def: 65,
      base_satt: 70,
      base_sdef: 70,
      base_spd: 70,
      reward: 100,
    },
    {
      id: 149,
      pic: '149.png',
      name: 'Dragonite',
      type: 'none',
      abilities: 'Inner Focus, Multiscale',
      base_hp: 91,
      base_att: 134,
      base_def: 95,
      base_satt: 100,
      base_sdef: 100,
      base_spd: 80,
      reward: 100,
    },
    {
      id: 150,
      pic: '150.png',
      name: 'Mewtwo',
      type: 'none',
      abilities: 'Pressure, Unnerve',
      base_hp: 106,
      base_att: 110,
      base_def: 90,
      base_satt: 154,
      base_sdef: 90,
      base_spd: 130,
      reward: 100,
    },
    {
      id: 151,
      pic: '151.png',
      name: 'Mew',
      type: 'none',
      abilities: 'Synchronize',
      base_hp: 100,
      base_att: 100,
      base_def: 100,
      base_satt: 100,
      base_sdef: 100,
      base_spd: 100,
      reward: 100,
    },
  ];

  constructor() {}

  ngOnInit(): void {}

  ngAfterContentInit(): void {
    this.getPokemon();
  }

  ngOnChanges() {
    this.getPokemon();
    this.getPokemonName();
  }

  getPokemon(): Pokemon {
    this.currentPokemon = this.pokedex[this.currentPokemonNumber];
    // console.log(this.currentPokemon);
    return this.currentPokemon;
  }

  getPokemonName() {
    this.currentPokemonName.emit(this.currentPokemon);
  }
}
